#%RAML 1.0
title: MiniProject

types:
  Article: !include Project_Types/articleType.raml

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    queryParameters:
      forceParams:
        required: false
    responses:
      401:
        description: Unauthorized, The client_id or client_secret are not valid or the client does not have access.
    

/articles:

  is: [client-id-required]

  get:
    description: Get All Articles 
    responses:
      200:
        body:
          application/json:
            type: Article[]
            examples:
              output : !include Project_TypesExemples/articles.json

  post:
    description: Add Articles
    body:
      application/json:
        type: array
        items: Article
        examples:
          input : !include Project_TypesExemples/articlesPOST.json
    responses:
      201:
        body:
          application/json:
            example:
              message : Article Added  

  put:
    description: Update a list of Articles
    body:
      application/json:
         type: Article[]
         examples:
           input: !include Project_TypesExemples/articles.json
    responses:
          200:
            body:
              application/json:
                example:
                  message: Articles updated (but not really)

  
  /{ID}:
    
    is: [client-id-required]
    
    get:
      description: Get All Articles 
      responses:
       200:
         body:
            application/json:
             type: Article
             examples:
                output: !include Project_TypesExemples/article.json
    
   
                
  

  

  







