#%RAML 1.0
title: MiniProject

types:
  Article: !include Project_Types/articleType.raml


/article:
  /{id}:
    get:
      description: Get All Articles 
      headers:
        username: string
        password: string
      responses:
       200:
         body:
            application/json:
             type: Article
             examples:
                output: !include Project_TypesExemples/article.json
    
    delete:
      description: Delete Article by ID
      headers:
        username: string
        password: string
      body:
        application/json:
          type: Article
          examples:
            input: !include Project_TypesExemples/article.json
      responses:
        200:
          body:
            application/json:
              example:
                message: Article deleted (but not really)

    put:
      description: Update Article by ID
      headers:
        username: string
        password: string
      body:
        application/json:
          type: Article
          examples:
            input: !include Project_TypesExemples/article.json
      responses:
          200:
            body:
              application/json:
                example:
                  message: Article updated (but not really)



  get:
    description: Get All Articles 
    headers:
      username: string
      password: string
    responses:
      200:
        body:
          application/json:
            type: Article[]
            examples:
              output : !include Project_TypesExemples/articles.json
 

  post:
    description: Add Article 
    headers:
      username: string
      password: string
    body:
      application/json:
        type: array
        items: Article
        examples:
          input : !include Project_TypesExemples/articlesPOST.json
    responses:
      201:
        body:
          application/json:
            example:
              message : Article Added   


  delete:
    description: Delete a list of Articles
    headers:
        username: string
        password: string
    body:
      application/json:
         type: Article[]
         examples:
           input: !include Project_TypesExemples/articles.json
     
    responses:
        200:
          body:
            application/json:
              example:
                message: Articles deleted (but not really)
            
  put:
    description: Update a list of Articles
    headers:
        username: string
        password: string
    body:
      application/json:
         type: Article[]
         examples:
           input: !include Project_TypesExemples/articles.json
    responses:
          200:
            body:
              application/json:
                example:
                  message: Articles updated (but not really)




# /auth:
#   get:
#     description: Get Connexion 
#     headers:
#         username: string
#         password: string
#     responses:
#         200:
#           body:
#             application/json:
#               example:
#                 message: Authentication Succeeded
#         401:
#           body:
#             application/json:
#               example:
#                 message: Authentication failed






